# Generated by Django 2.2.4 on 2022-01-11 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0002_answer_problem_solution'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='message',
            field=models.TextField(null=True),
        ),
    ]
